# Generated by Django 2.2.2 on 2020-01-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('0', 'Politics'), ('1', 'Sports'), ('2', 'Business'), ('3', 'International')], max_length=2),
        ),
    ]
